apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: control-plane-us-east-1a
  labels:
    kops.k8s.io/cluster: microsvc-prod.k8s.internal
spec:
  role: ControlPlane
  machineType: m6i.large
  minSize: 1
  maxSize: 1
  subnets:
    - us-east-1a
  rootVolumeSize: 64
  rootVolumeType: gp3
  rootVolumeEncryption: true
  instanceMetadata:
    httpTokens: required
    httpPutResponseHopLimit: 1
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: control-plane-us-east-1b
  labels:
    kops.k8s.io/cluster: microsvc-prod.k8s.internal
spec:
  role: ControlPlane
  machineType: m6i.large
  minSize: 1
  maxSize: 1
  subnets:
    - us-east-1b
  rootVolumeSize: 64
  rootVolumeType: gp3
  rootVolumeEncryption: true
  instanceMetadata:
    httpTokens: required
    httpPutResponseHopLimit: 1
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: control-plane-us-east-1c
  labels:
    kops.k8s.io/cluster: microsvc-prod.k8s.internal
spec:
  role: ControlPlane
  machineType: m6i.large
  minSize: 1
  maxSize: 1
  subnets:
    - us-east-1c
  rootVolumeSize: 64
  rootVolumeType: gp3
  rootVolumeEncryption: true
  instanceMetadata:
    httpTokens: required
    httpPutResponseHopLimit: 1
